### ISSUE TITLE
Submit the LLP header in network byte order

### ISSUE THREAD

**Issue by wizardone** [a2800276/8583#21]
Hi there,
this issue is a mixture of a proposal, issue and a question :).
If communicating via TCP Socket (if you are required to use the shitty iso8583 protocol you probably are) you will often be required to submit the iso8583 message, along with the LLP header (length of the message in network byte order). I tried implementing it, however I'm never able to calculate it properly. Therefore my questions are:
1. Do you plan on implementing something like this generically in the gem?
2. Can you provide a little assistance with my own approach for this? I would be happy to create a PR for this, if you want it to be included in the gem, once it is working properly..
I currently have something like this within the `ISO8583::Message` class:
binary representation of the message, prefixed with the length of the message, presented with 2 bytes.
```ruby
def stream
  message = to_b
  header = sprintf('%02d', message.length)
  header + message
end
```
Do you have an idea what would be the best way to approach this? I have to admit the internals of the iso8583 gem are not 100% familiar to me, maybe there is something relatively easy that can be changed, however I could not find it.

**Comment by a2800276** [comment]
First off, 8583 is a GREAT protocol  and TCP sockets are a lovely way to avoid the overhead of http . You should be GRATEFUL that you don't have to use x.25 (although in that case you wouldn't need the header ...)

As to 1.) no I have little plans to do more than maintenance. I'd be more than happy to incorporate any tested length header code you provide though.

2.) I'm not sure what problem you are having encoding the LLP length header. 8583 is pretty ambiguous, so I'd need to know which specs you're using to know for sure. I'll guess that the code you provided is not what you're looking for, it would format the length of the message as ascii (which MAY be what you want)

My interpretation of your header description is: length is encoded as 16bit (short) big-endian (network byte order). So, if your message is, e.g. ten bytes long: `{ 0x00, 0x00, 0x00, 0x00,0x00, 0x00,0x00, 0x00,0x00, 0x00}` , the header should be { 0x00, 0x0A}, the code you provided creates a header with the string "10" in it, i.e { 0x31, 0x30 }.

To create the header I decribed, either 
- use `pack` with a format of `n` (see the documentation for Array.pack or grep through the gem)
- just bit twiddle: `header = []; header[0] = (len >> 8) & 0xff; header[1] = len & 0xff`
- if you want to use one of the existing encoders, the `Packed_Number` codec does what you want.

It would be nice to add a utility method like `bmp` and `mti` to define the length prefixer along with your class, so it's automatically generated when you call `to_b` and checked during decoding...

Let me know if any of the above makes sense or not.

**Comment by wizardone** [comment]
@a2800276 Thank you for your quick response. Let me wrap my head around it and i will get back to you.

**Comment by a2800276** [comment]
Hi Stefan,

I added a Codec to handle encoding of the length prefix (see https://github.com/a2800276/8583/blob/master/lib/iso8583/codec.rb#L147)

I was considering adding code to the message declaration, that would handle the length prefix like the MTI and BMPs are handled, e.g.:

    class ExampleMessage < Message
        len_prefix BE_U16
        mti_format .... # same as before
        bmp ...
    end

This would automatically adds the prefix during `to_b` and checks/removes it during `parse`

But the more I think about it, the less convinced I am that this is useful, and would appreciate your opinion on the matter.

Receiving a prefixed message, would be handled somewhat like this:

    len_bytes = sock.read(2)
    len = BE_U16.decode(len_bytes)
    message_bytes = sock.read(len)
    message = MyMessage.parse(message_bytes)

because the library isn't doing any network / socket operations, there's no benefit for it to know how the message is prefixed on the network. Similarly when writing to the socket, only single additional line would be necessary:

    message_bytes = message.to_b
    sock.write(BE_U16.encode(message_bytes.size))
    sock.write(message_bytes)

So unless one would incorporate network handling code into the library, I don't think it makes sense to handle the length prefix in the `parse` and `to_b` functions.

Anyway, let me know if this makes sense and if this corresponds roughly with your use case. Like I said, I'm open to alternatives.

**Comment by wizardone** [comment]
@a2800276 First off, many thanks for your work and clarifications, they are much appreciated.
I pretty much tried a similar approach to the codec with `pack`, however I am still not able to achieve the desired result (keeping in mind that the problem may not be on my side). I will give it a try, using your new codec tomorrow and share results.
As far as the prefix goes I think you are absolutely right. Although it would be nice to have such functionality, I believe it to be a helper for transmitting the generated message, not part of the actual domain logic, therefore it is probably not well suited in here.

I would like to keep this issue opened for a couple more days, if you don't mind, I really like to share a working solution for this as soon as I have it, maybe others can benefit from it :)

**Comment by a2800276** [comment]
ok. good luck, let me know if I can help.
